"""
Automated Official Reporting Engine — draft generator.

This module is intentionally self-contained: it does not import
detect_pipeline, analysis_ensemble, or the security/safety-lock package, and
it does not modify their behavior. It reuses the same Granite Instruct
model_id configured for scan analysis (settings.MODEL_GRANITE_INSTRUCT) so the
draft is produced by "the same model used for analysis", per the brief, while
staying fully decoupled from the scan pipeline's own watsonx client code.

It never contacts cybercrime.gov.in or any external portal — it only
produces text for the user to review and copy/paste themselves.
"""
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from app.core.config import settings

logger = logging.getLogger(__name__)

RISK_LABEL = {"LOW": "Low", "MEDIUM": "Medium / Suspicious", "HIGH": "High"}


def _fmt_timestamp(raw: Optional[str]) -> str:
    if raw:
        try:
            # Accept ISO strings from the frontend (new Date().toISOString()).
            cleaned = raw.replace("Z", "+00:00")
            dt = datetime.fromisoformat(cleaned)
            return dt.strftime("%d %b %Y, %I:%M %p UTC")
        except Exception:
            return raw
    return datetime.now(timezone.utc).strftime("%d %b %Y, %I:%M %p UTC")


def _plain_language_description(scan_data: Dict[str, Any]) -> str:
    category = scan_data.get("scam_category", "a suspicious message")
    input_type = scan_data.get("input_type_used") or "message"
    input_type_label = {
        "text": "a text/SMS/WhatsApp message",
        "url": "a suspicious link (URL)",
        "image": "a screenshot",
        "qr": "a QR code",
    }.get(input_type, "a suspicious message")

    flags = scan_data.get("red_flags") or []
    flags_sentence = ""
    if flags:
        top_flags = "; ".join(flags[:4])
        flags_sentence = f" The content showed the following warning signs: {top_flags}."

    summary = scan_data.get("summary") or ""
    summary_sentence = f" {summary}" if summary else ""

    return (
        f"I received/encountered {input_type_label} that CyberRaksha's AI scam "
        f"detector identified as a likely case of {category}.{flags_sentence}"
        f"{summary_sentence}"
    ).strip()


def _suspect_details(scan_data: Dict[str, Any]) -> str:
    urls = scan_data.get("detected_urls") or []
    qr_payload = scan_data.get("qr_payload")
    lines: List[str] = []
    if urls:
        lines.append("Suspicious URL(s) involved:")
        lines.extend(f"  - {u}" for u in urls)
    if qr_payload:
        lines.append(f"Decoded QR code payload: {qr_payload}")
    if not lines:
        lines.append(
            "No specific phone number, UPI ID, or website was captured beyond what is "
            "described in the incident details above. Attach the original message or "
            "screenshot as evidence when submitting."
        )
    return "\n".join(lines)


def _evidence_summary(scan_data: Dict[str, Any]) -> str:
    parts = [
        "The content was analyzed by CyberRaksha's AI scam detector (IBM Granite models).",
    ]
    urls = scan_data.get("detected_urls") or []
    parts.append(f"Detected URLs: {', '.join(urls) if urls else 'None'}.")
    similarity = scan_data.get("similarity_match")
    if similarity:
        note = similarity.get("note") or similarity.get("category")
        if note:
            parts.append(f"This message closely matches a previously reported scam pattern: {note}.")
    parts.append(
        "Please attach the original message, screenshot, call recording, or transaction "
        "reference as supporting evidence when you submit this report."
    )
    return " ".join(parts)


def _local_fallback_draft(scan_data: Dict[str, Any]) -> str:
    """Deterministic, template-based draft used when watsonx isn't configured
    or the live call fails — mirrors the structure the live prompt asks for."""
    risk_level = scan_data.get("risk_level", "MEDIUM")
    risk_score = scan_data.get("risk_score", 0)
    category = scan_data.get("scam_category", "Suspected Online Fraud")
    dna = scan_data.get("scam_dna") or {}
    timestamp_str = _fmt_timestamp(scan_data.get("timestamp"))

    dna_line = (
        f"Urgency {dna.get('urgency', 0)}%, Fear {dna.get('fear', 0)}%, "
        f"Impersonation {dna.get('impersonation', 0)}%, Suspicious Link "
        f"{dna.get('suspicious_link', 0)}%, Payment Pressure {dna.get('payment_pressure', 0)}%"
    )

    return f"""NATIONAL CYBER CRIME REPORTING PORTAL — DRAFT COMPLAINT
(Auto-generated by CyberRaksha. Review every field before submitting at cybercrime.gov.in)

1. CATEGORY OF COMPLAINT
{category} (report under Financial Fraud / Online Fraud on the portal, as applicable)

2. DATE & TIME OF INCIDENT
{timestamp_str}

3. COMPLAINANT DETAILS (fill in before submitting — CyberRaksha does not collect this)
Name: [Your full name]
Mobile Number: [Your registered mobile number]
Email: [Your email address]
State / UT: [Your state]

4. DESCRIPTION OF INCIDENT
{_plain_language_description(scan_data)}

5. SUSPECT / FRAUDULENT DETAILS
{_suspect_details(scan_data)}

6. EVIDENCE SUMMARY
{_evidence_summary(scan_data)}

7. SUGGESTED SEVERITY / RISK ASSESSMENT
Risk Level: {RISK_LABEL.get(risk_level, risk_level)} ({risk_score}/100)
Scam DNA Breakdown: {dna_line}
""".strip()


def _build_prompt(scan_data: Dict[str, Any]) -> str:
    dna = scan_data.get("scam_dna") or {}
    timestamp_str = _fmt_timestamp(scan_data.get("timestamp"))
    flags = scan_data.get("red_flags") or []
    urls = scan_data.get("detected_urls") or []

    return (
        "You are helping an Indian user pre-fill a complaint draft for India's National "
        "Cyber Crime Reporting Portal (cybercrime.gov.in), based on an AI scam scan result. "
        "You are NOT submitting anything — only drafting text the user will review and "
        "copy into the portal themselves. Do not invent facts not given below. Leave the "
        "complainant's personal details as placeholders in square brackets, since you were "
        "not given that information.\n\n"
        "SCAN DATA:\n"
        f"- Scam category: {scan_data.get('scam_category')}\n"
        f"- Risk level: {scan_data.get('risk_level')} (score {scan_data.get('risk_score')}/100)\n"
        f"- Red flags: {'; '.join(flags) if flags else 'none listed'}\n"
        f"- Scam DNA breakdown: urgency={dna.get('urgency', 0)}, fear={dna.get('fear', 0)}, "
        f"impersonation={dna.get('impersonation', 0)}, suspicious_link={dna.get('suspicious_link', 0)}, "
        f"payment_pressure={dna.get('payment_pressure', 0)}\n"
        f"- Detected URLs: {', '.join(urls) if urls else 'none'}\n"
        f"- QR payload: {scan_data.get('qr_payload') or 'none'}\n"
        f"- Analyst summary: {scan_data.get('summary') or 'none'}\n"
        f"- Incident date/time: {timestamp_str}\n\n"
        "Write a plain-text draft with these exact numbered sections, each on its own "
        "line with a blank line between sections:\n"
        "1. CATEGORY OF COMPLAINT\n"
        "2. DATE & TIME OF INCIDENT\n"
        "3. COMPLAINANT DETAILS (use bracketed placeholders: [Your full name], "
        "[Your registered mobile number], [Your email address], [Your state])\n"
        "4. DESCRIPTION OF INCIDENT (plain language, 2-4 sentences, based only on the scan data)\n"
        "5. SUSPECT / FRAUDULENT DETAILS (list URLs/UPI/QR payload if given, else say none captured)\n"
        "6. EVIDENCE SUMMARY (mention attaching the original message/screenshot)\n"
        "7. SUGGESTED SEVERITY / RISK ASSESSMENT (state the risk level, score, and DNA breakdown)\n\n"
        "Output only the draft text, no preamble, no markdown formatting, no extra commentary.\n"
    )


class ReportDraftGenerator:
    """Isolated service for the reporting engine. Never touches the scan
    pipeline, ensemble voting, or safety-lock code."""

    def __init__(self):
        self._api_available = bool(
            settings.IBM_WATSONX_API_KEY and settings.IBM_WATSONX_API_KEY != "your_ibm_cloud_api_key_here"
        )
        self._credentials = (
            {"url": settings.IBM_WATSONX_REGION_URL, "apikey": settings.IBM_WATSONX_API_KEY}
            if self._api_available
            else None
        )

    async def generate(self, scan_data: Dict[str, Any]) -> Dict[str, Any]:
        draft_text = _local_fallback_draft(scan_data)
        api_mode = "local_fallback"

        if self._api_available:
            try:
                from ibm_watsonx_ai.foundation_models import ModelInference

                space_id = getattr(settings, "IBM_WATSONX_SPACE_ID", "") or None
                project_id = settings.IBM_WATSONX_PROJECT_ID or None
                scope_kwargs = {"space_id": space_id} if space_id else {"project_id": project_id}

                model = ModelInference(
                    model_id=settings.MODEL_GRANITE_INSTRUCT,
                    params={"max_new_tokens": 700},
                    credentials=self._credentials,
                    **scope_kwargs,
                )
                generated = model.generate_text(prompt=_build_prompt(scan_data))
                generated = (generated or "").strip()
                if generated:
                    draft_text = generated
                    api_mode = "live_watsonx"
            except Exception as exc:
                logger.warning(f"Report draft generation via watsonx failed, using local fallback: {exc}")
                api_mode = f"local_fallback (watsonx unavailable: {exc})"

        return {
            "draft_text": draft_text,
            "api_mode": api_mode,
            "model_used": settings.MODEL_GRANITE_INSTRUCT,
            "generated_at": _fmt_timestamp(scan_data.get("timestamp")),
        }


report_draft_generator = ReportDraftGenerator()
